title: "Nav Link, Secondary"
label: "Nav Link, Secondary"
notes: "Style for a nav link appearing in secondary navigation like the footer or sidebar."
status: "ready"
context:
  linkurl: "http://www.aaronpinero.com"
  linktext: "Aaron Pinero"
  modifier: "default"
variants:
  - name: "github"
    title: "with Github Icon"
    label: "with Github Icon"
    notes: "Nav link with the github logo"
    context:
      linkurl: "https://github.com/aaronpinero/typography"
      linktext: "Fork on Github"
      modifier: "github"
  - name: "npm"
    title: "with npm Icon"
    label: "with npm Icon"
    notes: "Nav link with the npm logo"
    context:
      linkurl: "https://www.npmjs.com/package/tyfy"
      linktext: "npm install tyfy"
      modifier: "npm"
